version: '3'
services:

  web:
    image: nginx:latest
    ports:
      - ${http_port}:80
      - ${https_port}:443
    env_file: 
      - .env    
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./certificados:/etc/nginx/certificados
  apache1:
    build: apache  
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html
  apache2:
    build: apache  
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html
  apache3:
    build: apache  
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html            
