version: '3'
services:

  web:
    image: nginx:latest
    env_file: .env    
    ports:
      - ${http_port}:80
      - ${https_port}:443
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./certificados:/etc/nginx/certificados
    environment:
      - ServerName=${ServerName}
      - http_port=${http_port}
      - https_port=${https_port}
      - Certificado=${Certificado}
      - Chave=${Chave}

  apache1:
    build: apache  
    env_file: .env
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html
    Environment:
      - ServerName=${ServerName}
  apache2:
    build: apache  
    env_file: .env
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html
    Environment:
      - ServerName=${ServerName}
  apache3:
    build: apache  
    env_file: .env
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./html:/html            
    Environment:
      - ServerName=${ServerName}